version: "3"

services:
  mysql000ex11:
    image: mysql:5.7
    platform: linux/amd64
    networks:
      - wordpress000net1
    volumes:
      - mysql000vol11:/var/lib/myql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hihi
      MYSQL_DATABASE: wordpress000db
      MYSQL_USER: kyle
      MYSQL_PASSWORD: hihi

  wordpress000ex12:
    depends_on:
      - mysql000ex11
    image: wordpress
    networks:
      - wordpress000net1
    volumes:
      - wordpress000vol12:/var/www/html
    ports:
      - 8085:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql000ex11
      WORDPRESS_DB_NAME: wordpress000db
      WORDPRESS_DB_USER: kyle
      WORDPRESS_DB_PASSWORD: hihi

networks:
  wordpress000net1:

volumes:
  mysql000vol11:
  wordpress000vol12:
